% Compare taub estimates from FrictionAlpha2 and equations

root='/Users/badgeley/projects/seasonality/Cryo23';
file='Model_NW_TransientInversionRun_indep5_2018.5_2020.1_fric2_catchment36_reg1000vel200prior0rhe0';

md=loadmodel(fullfile(root,file));

taub_alpha=basal_shear_stress_alpha( ...
                  [md.results.TransientSolution(:).FrictionAlpha2], ...
                  [md.results.TransientSolution(:).Vel]./md.constants.yts);

N=effective_pressure_full_connectivity( ...
                          [md.results.TransientSolution(:).Thickness], ...
                          [md.results.TransientSolution(:).Base], ...
                          md.constants.g, ...
                          md.materials.rho_ice, ...
                          md.materials.rho_water, ...
                          0.01);

taub_schoof=basal_shear_stress_schoof( ...
              [md.results.TransientSolution(:).FrictionC], ...
              N, ...
              [md.results.TransientSolution(:).Vel]./md.constants.yts, ...
              3, ...
              0.5);

disp([min(taub_alpha-taub_schoof,[],'all'),...
     mean(taub_alpha-taub_schoof,'all'), ...
     max(taub_alpha-taub_schoof,[],'all')]);

plotmodel(md,'data',max(abs(taub_alpha-taub_schoof),[],2));