% Compare taub estimates from FrictionAlpha2 and equations

root='/Users/badgeley/projects/seasonality/Cryo23';
file='Model_NW_TransientInversionRun_indep5_2018.5_2020.1_fric3_catchment36_reg100vel200prior0rhe0';

md=loadmodel(fullfile(root,file));

taub_alpha=basal_shear_stress_alpha( ...
                  [md.results.TransientSolution(:).FrictionAlpha2], ...
                  [md.results.TransientSolution(:).Vel]./md.constants.yts);

N=effective_pressure_full_connectivity( ...
                          [md.results.TransientSolution(:).Thickness], ...
                          [md.results.TransientSolution(:).Base], ...
                          md.constants.g, ...
                          md.materials.rho_ice, ...
                          md.materials.rho_water, ...
                          0);

taub_budd=basal_shear_stress_budd( ...
             [md.results.TransientSolution(:).FrictionCoefficient], ...
             N, ...
             [md.results.TransientSolution(:).Vel]./md.constants.yts, ...
             6,6);

disp([min(taub_alpha-taub_budd,[],'all'),...
     mean(taub_alpha-taub_budd,'all'), ...
     max(taub_alpha-taub_budd,[],'all')]);

plotmodel(md,'data',max(abs(taub_alpha-taub_budd),[],2),'caxis',[0,100]);