function N = effective_pressure_full_connectivity(H, ...
                                                  base, ...
                                                  g, ...
                                                  rho_ice, ...
                                                  rho_water, ...
                                                  effective_pressure_limit)
%EFFECTIVE_PRESSURE_FULL_CONNECTVITY: This function calculates subglacial
%effective pressure assuming that the subglacial system is fully connected
%to the ocean. 
%   INPUTS: 
%           H: vector of ice thicknesses (m) for different locations. Can 
%              also be a matrix to include how thickness evolves in time.
%           B: vector of ice base elevations (m) for different locations
%           g: acceleration due to gravity (m/s) - usually 9.81
%           rho_ice: density of ice (kg/m^3) - usually 917
%           rho_water: density of seawater (kg/m^3) - usually 1027
%           effective_pressure_limit: minimum value of effective pressure
%                                     (Pa). Generally this can be 0 unless
%                                     using certain friction laws like
%                                     Schoof where N is in the denominator.
%   OUTPUTS: 
%           N: effective pressure (Pa) with same dimentions as H 
%   EXAMPLE: 
%           N = effective_pressure_full_connectivity( ...
%                      [md.results.TransientSolution(:).Thickness], ...
%                      [md.results.TransientSolution(:).Base], ...
%                      md.constants.g, ...
%                      md.materials.rho_ice, ...
%                      md.materials.rho_water, ...
%                      0.01);
N=(rho_ice*H*g)-(rho_water*(0-base)*g);
N(N<=effective_pressure_limit)=effective_pressure_limit;
 
end